name: service-api
resources:
  containers:
  - container: kaniko
    image: 'gcr.io/kaniko-project/executor:$(kaniko-version)'
trigger:
- stable-azure

stages:
- stage: assemble
  jobs:
  - job: build
    pool: 
      vmImage: $(vm-image)
    steps:
    - bash: |
        version=`cat $(version-file)  | grep $(version-property) | cut -d '=' -f2-`
        echo "##vso[task.setvariable variable=snapshotVersion]$version"
      name: getSnapshotVersion
    - bash: |
        echo "my environment variable is $snapshotVersion"

