name: service-api
resources:
  containers:
  - container: kaniko
    image: 'gcr.io/kaniko-project/executor:$(kaniko-version)'
trigger:
- stable-azure
variables:
  service_repo: 'reportportaldemo.azurecr.io/service-api'

stages:
- stage: assemble
  jobs:
  - job: build
    pool: 
      vmImage: $(vm-image)
    steps:
    - bash: |
        snapshot_version=`cat $(version-file) | grep $(version-property) | cut -d '=' -f2-`
        echo "##vso[task.setvariable variable=snapshot_version]$snapshot_version"

        build_version=`echo BUILD-$(Build.BuildId)`
        echo "##vso[task.setvariable variable=build_version]$build_version"
        
        service_version=`echo "${snapshot_version}-${build_version}"`
        echo "##vso[task.setvariable variable=service_version]$service_version"
        tag=`echo "$(service_repo):$service_version"`
        echo "##vso[task.setvariable variable=tag]$tag"
      name: getVersions
    - bash: |
        echo "$SNAPSHOT_VERSION"
        echo "$BUILD_VERSION"
        echo "$SERVICE_VERSION"
        echo "$TAG"

