name: service-api
resources:
  containers:
  - container: kaniko
    image: 'gcr.io/kaniko-project/executor:$(kaniko-version)'
trigger:
- stable-azure
variables:
  serviceRepo: 'reportportaldemo.azurecr.io/service-api'

stages:
- stage: assemble
  jobs:
  - job: build
    pool: 
      vmImage: $(vm-image)
    steps:
    - bash: |
        snapshotVersion=`cat $(version-file) | grep $(version-property) | cut -d '=' -f2-`
        echo "##vso[task.setvariable variable=snapshotVersion;isOutput=true]$snapshotVersion"

        buildVersion=`echo AZURE-BUILD-$(Build.BuildId)`
        echo "##vso[task.setvariable variable=buildVersion;isOutput=true]$buildVersion"
        
        serviceVersion=`echo "${snapshotVersion}-${buildVersion}"`
        echo "##vso[task.setvariable variable=serviceVersion;isOutput=true]$serviceVersion"
        tag=`echo "$serviceVersion" | tr '[:upper:]' '[:lower:]'`
        echo "##vso[task.setvariable variable=tag;isOutput=true]$tag"
      name: getVersions
      displayName: 'Get application versions'
    - bash: |
        echo "$(getVersions.snapshotVersion)"
        echo "$(getVersions.buildVersion)"
        echo "$(getVersions.serviceVersion)"
        echo "$(getVersions.tag)"
      displayName: 'Print application versions'

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        repository: $(repository)
        containerRegistry: gcr-rp-demo

    - task: Docker@2
      displayName: Build container
      inputs:
        command: build
        Dockerfile: 'docker/Dockerfile-develop'
        repository: $(repository)
        tags: '$(getVersions.tag)'
        buildContext: '$(Build.Repository.LocalPath)'
        arguments: '--build-arg buildNumber=$(getVersions.buildVersion)'

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(repository)
        tags: '$(getVersions.tag)'

    - task: Docker@2
      displayName: Logout from ACR
      inputs:
        command: logout
        containerRegistry: gcr-rp-demo