name: test
resources:
  repositories:
    - repository: jdiRest
      type: github
      name: jdi-examples/jdi-dark-report-portal-demo
      endpoint: reportportal
    - repository: jdiUi
      type: github
      name: jdi-examples/jdi-light-report-portal-demo
      endpoint: reportportal
    - repository: jdiMobile
      type: github
      name: jdi-examples/jdi-mobile-report-portal-demo
      endpoint: reportportal

trigger: none

stages:
- stage: test

  jobs:
  - job: apiTests
    pool: 
      vmImage: $(vm-image)
    steps:
    - checkout: jdiRest

    - task: Kubernetes@1
      displayName: 'Login to kubernetes'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'gke-rp-demo'
        namespace: 'reportportal'
        command: 'login'
    
    - bash: |
        `kubectl get secret ${SECRET} -o json -n ci | jq -r '.data | to_entries | map([.key, .value]|join("="))|join("\n")'|sed -E -n 's/([^=]+)=(.+)/echo "##vso[task.setvariable variable=\1;isOutput=true;issecret=true]$(echo "\2" | base64 -d)"/ p' >credentials.sh`
        source credentials.sh
      name: getSecretsStep
      env:
        SECRET: jdi-test-secret
      displayName: 'Get test secrets'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: >-
          -Dsut.username=$(getSecretsStep.TEST_USER_LOGIN)
          -Dsut.password=$(getSecretsStep.TEST_USER_PASSWORD)
          -Pdev_env -Preport
          -Dbuild.tag="AZURE-BUILD-$(Build.BuildId)"
          -Drp.uuid=$(getSecretsStep.RP_UUID)
          -Drp.project=$(getSecretsStep.RP_PROJECT)
          -Drp.enable=true
          -Drp.endpoint=$(getSecretsStep.RP_URL)
          -Drp.attributes="env:dev-gcp;type:api;runner:azure"
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'API tests'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    
  - job: uiTests
    pool: 
      vmImage: $(vm-image)
    steps:
    - checkout: jdiUi

    - task: Kubernetes@1
      displayName: 'Login to kubernetes'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'gke-rp-demo'
        namespace: 'reportportal'
        command: 'login'

    - bash: |
        `kubectl get secret ${SECRET} -o json -n ci | jq -r '.data | to_entries | map([.key, .value]|join("="))|join("\n")'|sed -E -n 's/([^=]+)=(.+)/echo "##vso[task.setvariable variable=\1;isOutput=true;issecret=true]$(echo "\2" | base64 -d)"/ p' >credentials.sh`
        source credentials.sh
      name: getSecretsStep
      env:
        SECRET: jdi-test-secret
      displayName: 'Get test secrets'

    - bash: |
        `kubectl get secret ${SECRET} -o json -n ci | jq -r '.data | to_entries | map([.key, .value]|join("="))|join("\n")'|sed -E -n 's/([^=]+)=(.+)/export KEY=\2/ p' >credentials.sh`
        source credentials.sh
        echo 'echo "##vso[task.setvariable variable=SAUCELABS_URL;isOutput=true;issecret=true]$(saucelabs-url)"' >url.sh
        source url.sh
      name: getSaucelabsSecretStep
      env:
        SECRET: saucelabs-accesskey
      displayName: 'Get saucelabs secret'

    - bash: |
        `kubectl get secret ${SECRET} -o json -n ci | jq -r '.data | to_entries | map([.key, .value]|join("="))|join("\n")'|sed -E -n 's/([^=]+)=(.+)/echo "##vso[task.setvariable variable=\1;isOutput=true;issecret=true]$(echo "\2" | base64 -d)"/ p' >credentials.sh`
        source credentials.sh
      name: getMinioSecretStep
      env:
        SECRET: minio-genrocket
      displayName: 'Get minio secret'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: >-
          -Pdefault
          -Dtest=!GenRocketLoginTest
          -Drp.uuid=$(getSecretsStep.RP_UUID)
          -Drp.project=$(getSecretsStep.RP_PROJECT)
          -Drp.enable=true
          -Drp.endpoint=$(getSecretsStep.RP_URL)
          -Drp.attributes="env:dev-gcp;type:ui;runner:azure"
          -Dreport.portal.user=$(getSecretsStep.TEST_USER_LOGIN)
          -Dreport.portal.password=$(getSecretsStep.TEST_USER_PASSWORD)
          -Dminio.url=http://minio-genrocket.ci.svc.cluster.local:9000
          -Dminio.accesskey=$(getMinioSecretStep.ACCESSKEY)
          -Dminio.secretkey=$(getMinioSecretStep.SECRETKEY)
          -Dwebdriver.remote.url=$(getSaucelabsSecretStep.SAUCELABS_URL)
          -Dbuild.tag="AZURE-BUILD-$(Build.BuildId)"
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'UI tests'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

  - job: mobileTests
    pool: 
      vmImage: $(vm-image)
    steps:
    - checkout: jdiMobile

    - task: Kubernetes@1
      displayName: 'Login to kubernetes'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'gke-rp-demo'
        namespace: 'reportportal'
        command: 'login'

    - bash: |
        `kubectl get secret ${SECRET} -o json -n ci | jq -r '.data | to_entries | map([.key, .value]|join("="))|join("\n")'|sed -E -n 's/([^=]+)=(.+)/echo "##vso[task.setvariable variable=\1;isOutput=true;issecret=true]$(echo "\2" | base64 -d)"/ p' >credentials.sh`
        source credentials.sh
      name: getSecretsStep
      env:
        SECRET: jdi-test-secret
      displayName: 'Get test secrets'

    - bash: |
        `kubectl get secret ${SECRET} -o json -n ci | jq -r '.data | to_entries | map([.key, .value]|join("="))|join("\n")'|sed -E -n 's/([^=]+)=(.+)/\1=$(echo "\2" | base64 -d)/ p' >credentials.sh`
        source credentials.sh
        echo 'echo "##vso[task.setvariable variable=SAUCELABS_URL;isOutput=true;issecret=true]$(saucelabs-url)"' >url.sh
        source url.sh
      name: getSaucelabsSecretStep
      env:
        SECRET: saucelabs-accesskey
      displayName: 'Get saucelabs secret'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        options: >-
          -Dreport.portal.user=$(getSecretsStep.TEST_USER_LOGIN)
          -Dreport.portal.password=$(getSecretsStep.TEST_USER_PASSWORD)
          -Dwebdriver.remote.url=$(getSaucelabsSecretStep.SAUCELABS_URL)
          -Dmobile.platform.name=Android
          -Dmobile.platform.version=10
          -Dmobile.device.name="Google Pixel 2"
          -Dmobile.device.orientation=portrait
          -Dbuild.tag="AZURE-BUILD-$(Build.BuildId)"
          -Drp.uuid=$(getSecretsStep.RP_UUID)
          -Drp.project=$(getSecretsStep.RP_PROJECT)
          -Drp.enable=true
          -Drp.endpoint=$(getSecretsStep.RP_URL)
          -Drp.attributes="env:dev-gcp;type:mobile;runner:azure"
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        testRunTitle: 'Mobile tests'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
