language: java
dist: xenial
sudo: required

before_install:
  - sudo apt-get install -y fonts-noto
  - ./gradlew build --no-build-cache --info
script: ./gradlew assemble --info

env:
  global:
    - GRADLE_OPTS="-Xms128m -Xmx1g"

jdk:
  - openjdk11

matrix:
  include:
    - jdk: openjdk11
      before_install:
        - sudo rm "${JAVA_HOME}/lib/security/cacerts"
        - sudo ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

notifications:
  slack: reportportal-dev:fl6xWHVQp1jvsMmCJxYW9YKP

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:

after_success:
  - bash <(curl -s https://codecov.io/bash)
