spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${rp.db.url}
  rabbitmq:
    addresses: ${rp.amqp.addresses}

rp:
  amqp:
    addresses: amqp://rabbitmq:rabbitmq@localhost:5672
    api-address: http://rabbitmq:rabbitmq@localhost:15672/api
  db:
    url: jdbc:postgresql://localhost:5432/reportportal?user=rpuser&password=rppass

logging:
  level:
    org:
      hibernate:
        SQL: debug