spring:
  cloud:
    consul:
      discovery:
        hostname: docker.for.win.localhost
      host: localhost
rp:
  uat:
    serviceUrl: http://localhost:8080/uat
  analyzer:
    url: http://localhost:8080/analyzer
  db:
    url: jdbc:postgresql://localhost:5432/reportportal?user=rpuser&password=rppass
  amqp:
    url: amqp://rabbitmq:rabbitmq@localhost:5672