server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:api}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://uat:9999/sso/me
    client:
      access-token-uri: http://uat:9999/sso/oauth/token
      user-authorization-uri: http://uat:9999/sso/oauth/authorize
      client-id: internal
      client-secret: internal_man

rp:
  mongo:
    host: mongodb
    port: 27017
    dbName: reportportal
    user:
    password:

spring:
  redis:
    host: redis
    port: 6379
  cloud:
    consul:
      host: consul
      discovery:
        hostname: api
        prefer-ip-address: false
