rp:
  amqp:
    host: localhost
  db:
    host: localhost
  plugins:
    rootDir: plugins
  datasource:
    maximumPoolSize: 5
  binarystore:
  type: filesystem
    path: ${java.io.tmpdir}${file.separator}reportportal${file.separator}datastore

logging:
  file: ${java.io.tmpdir}${file.separator}reportportal${file.separator}logs${file.separator}${spring.application.name}.log
  level:
    org:
      hibernate:
        SQL: info