rp:
  uat:
    serviceUrl: http://localhost:8080/uat
  analyzer:
    url: http://localhost:8080/analyzer
  amqp:
    host: localhost
  db:
    host: localhost
  plugins:
    path: plugins
logging:
  level:
    org:
      hibernate:
        SQL: debug