rp:
  uat:
    serviceUrl: http://localhost:8080/uat
  analyzer:
    url: http://localhost:8080/analyzer
  db:
    url: jdbc:postgresql://localhost:5432/reportportal?user=rpuser&password=rppass
  amqp:
    addresses: amqp://guest:guest@localhost:5672
    api-address: http://guest:guest@localhost:15672/api
  plugins:
    path: plugins
logging:
  level:
    org:
      hibernate:
        SQL: debug