rp:
  upload:
    maxUploadSize: 128MB
    maxFileSize: 32MB

spring:
  profiles:
    ## Default one is still Eureka
    active: ${rp.profiles:eureka}
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        tags:
          - urlprefix-${server.contextPath}
          - traefik.frontend.rule=PathPrefixStrip:/api
        healthCheckPath: ${server.contextPath}/admin/health
        host-info: ${server.contextPath}/admin/info
        ip-address: 10.200.10.1
        prefer-ip-address: true
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    status-page-url-path: ${server.contextPath}${management.contextPath}/info
    health-check-url-path: ${server.contextPath}${management.contextPath}/health



## Consul as service registry
---
spring:
  profiles: eureka
  cloud:
    consul:
      enabled: false
      discovery:
        register: false

## Consul as service registry
---
spring:
  profiles: consul
  cloud:
    consul:
      enabled: true
      discovery:
        register: true
eureka:
  client:
    register-with-eureka: false
    enabled: false
---
